name = "ngoctrung05hd/contractplutusv2"
version = "0.0.0"
license = "Apache-2.0"
target = "plutus:v2"
description = "Aiken contracts for project 'contractplutusv2'"

[repository]
user = "ngoctrung05hd"
project = "contractplutusv2"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
