name = "ngoctrung05hd/contract"
version = "0.0.0"
compiler = "v1.1.16"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'ngoctrung05hd/contract'"

[repository]
user = "ngoctrung05hd"
project = "contract"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
